name: Create Scratch Org

on:
  repository_dispatch:
    types: [trigger-scratch-org]

jobs:
  create_scratch_org:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli

      - name: Authenticate Dev Hub
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > authfile.json
          sfdx auth:sfdxurl:store -f authfile.json -a DevHub -d
          
      - name: Create Scratch Org
        run: |
          sfdx force:org:create -s -f config/project-scratch-def.json -a MyScratchOrg

      - name: List Orgs
        run: sfdx force:org:list
