name: Create Scratch Org

on:
  repository_dispatch:
    types: [create_scratch_org]

jobs:
  create-scratch-org:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli

      - name: Authenticate DevHub
        run: |
          echo $SFDX_AUTH_URL
          echo "$SFDX_AUTH_URL" > authfile.json
          sfdx force:auth:sfdxurl:store -f authfile.json -a DevHub -d

        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}

      - name: Create Scratch Org
        run: |
          sfdx force:config:set defaultdevhubusername=DevHub
          sfdx force:org:create -f config/project-scratch-def.json -a MyScratchOrg -d 1
