name: Create Scratch Org

on:
  repository_dispatch:
    types: [create_scratch_org]

jobs:
  create-scratch-org:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli

      - name: Authenticate DevHub
        run: |
          echo "Checking environment variables..."
          env  # Lists all environment variables (for debugging)
          
          echo "Printing SFDX_AUTH_URL..."
          echo "${{ secrets.SFDX_AUTH_URL }}" # This should print the value
          echo "$SFDX_AUTH_URL"  # This should also print it
      
          echo "Saving SFDX_AUTH_URL to file..."
          echo "${{ secrets.SFDX_AUTH_URL }}" > authfile.json
      
          cat authfile.json  # Check if the file is created
      
          echo "Authenticating with Salesforce..."
          sfdx force:auth:sfdxurl:store -f authfile.json -a DevHub -d
      
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}

      - name: Create Scratch Org
        run: |
          sfdx force:config:set defaultdevhubusername=DevHub
          sfdx force:org:create -f config/project-scratch-def.json -a MyScratchOrg -d 1
